#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "mxCynicc"
email = "xuqi.wang@stepai.cn"

[ui]
pager = "cat" # 设置为空字符串以禁用分页器
# default-command = ["log", "--limit=8"]
bookmark-list-sort-keys = ["committer-date-"]
default-command = "log"
diff-editor = ":builtin"

# [template-aliases]
# 'commit_timestamp(commit)' = 'commit.author().timestamp()'


[remotes.origin]
auto-track-bookmarks = "glob:*"
