add_newline = false
# å®šä¹‰ Prompt çš„æ˜¾ç¤ºæ ¼å¼ï¼Œåˆ æ‰äº† $git_branch å’Œ $git_status
format = """$os\
$username\
$hostname\
$localip\
$shlvl\
$directory\
${custom.jj_bookmark}\
${custom.jj} \
$rust\
$python\
$lua\
$nodejs\
$fill\
$cmd_duration\
$time\
$line_break\
$character"""

# è¿™é‡Œçš„ $fill å¯ä»¥æŠŠè·¯å¾„å’Œåé¢çš„æ—¶é—´ä¿¡æ¯æ’‘å¼€ï¼ˆå¦‚æœéœ€è¦çš„è¯ï¼‰
[fill]
symbol = " "


[os]
disabled = false
style = "bold blue" # ä½ å¯ä»¥æ ¹æ®å–œå¥½æ”¹é¢œè‰²
[os.symbols]
Arch = "ó°£‡ "

[directory]
truncation_length = 3
style = "bold cyan"

# custom module for jj status
[custom.jj_bookmark]
description = "The current jj markbook"
when = "jj --ignore-working-copy root"
symbol = "ó±—† "
style = "bold blue"
ignore_timeout = true
command = '''
BOOKMARK=$(jj log -r "latest(ancestors(@) & bookmarks())" --ignore-working-copy --no-graph -T "bookmarks.map(|b| b.name()).join(\",\")" -n 1)
echo "$BOOKMARK:"
'''

[custom.jj]
description = "The current jj status"
when = "jj --ignore-working-copy root"
symbol = ""
style = "bold blue"
command = '''
JJ_LOG=$(jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template "
  separate(\"\",
    change_id.shortest(4),
    \"| \",
    concat(
      if(conflict, \"ğŸ’¥ \"),
      if(divergent, \"ğŸš§ \"),
      if(hidden, \"ğŸ‘» \"),
      if(immutable, \"ğŸ”’ \"),
    ),
    raw_escape_sequence(\"\\x1b[1;32m\") ++ if(empty, \"(empty)\"),
    raw_escape_sequence(\"\\x1b[1;32m\") ++ coalesce(
      truncate_end(29, description.first_line(), \"â€¦\"),
      \"(no description set)\",
    ) ++ raw_escape_sequence(\"\\x1b[0m\"),
  )
")
echo "$JJ_LOG"
'''

# optionally disable git modules when JJ is found.
# note that you'll need to add ${custom.git_branch}, ${custom.git_commit} etc
# into format: https://starship.rs/config/#default-prompt-format
[git_status]
disabled = true

[custom.git_status]
when = "! jj --ignore-working-copy root"
command = "starship module git_status"
style = ""                                                     # This disables the default "(bold green)" style
description = "Only show git_status if we're not in a jj repo"

[git_commit]
disabled = true

[custom.git_commit]
when = "! jj --ignore-working-copy root"
command = "starship module git_commit"
style = ""
description = "Only show git_commit if we're not in a jj repo"

[git_metrics]
disabled = true

[custom.git_metrics]
when = "! jj --ignore-working-copy root"
command = "starship module git_metrics"
description = "Only show git_metrics if we're not in a jj repo"
style = ""

[git_branch]
disabled = true

[git_state]
disabled = true

[custom.git_branch]
when = "! jj --ignore-working-copy root"
command = "starship module git_branch"
description = "Only show git_branch if we're not in a jj repo"
style = ""


[time]
disabled = false
format = "[$time]($style)"
style = "bold fg:#39c5bb"
# è®¾ç½®æ—¶é—´æ ¼å¼ï¼ˆä¾‹å¦‚ 15:30:05ï¼‰
time_format = "%T"

[character]
# å°†é»˜è®¤çš„ â¯ æ›¿æ¢ä¸º Î»
success_symbol = "[Î»](bold green)"
error_symbol = "[Î»](bold red)"
